package classi;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

public class Frame extends javax.swing.JFrame {

    ArrayList<Corso> listaCorsi = new ArrayList<Corso>();

    /**
     * Creates new form WinGestione
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void btnCreaCorsoActionPerformed(java.awt.event.ActionEvent evt) {
        // Recuperiamo i dati da interfaccia
        String nomeCorso = txNomeCorso.getText();
        String descrizione = txDescrizione.getText();
        String data = txDataInizio.getText();
        String arrayData[] = data.split("/");
        int giorno = Integer.parseInt(arrayData[0]);
        int mese = Integer.parseInt(arrayData[1]);
        int anno = Integer.parseInt(arrayData[2]) + 2000;
        String link = txLinkCorso.getText();
        int durata = (int) spDurata.getValue();
        Corso nuovoCorso = new Corso(nomeCorso, durata, link, anno, mese, giorno);
        nuovoCorso.setDescrizioneCorso(descrizione);
        // nuovoCorso.setLink(link);
        listaCorsi.add(nuovoCorso);
        lblMsg.setText("Corso creato correttamente...");
        txNomeCorso.setText("");
        txDescrizione.setText("");
        txDataInizio.setText("");
        spDurata.setValue(0);

        // mostra elenco aggiornato nel display di listacorsi
        mostraCorsi();
        // salvo il corso creato sul file corsi.txt
        salvaCorsi();
        salvaCorsiCsv();

    }

    private void mostraCorsi() {
        /*
         * - recupero un corso per volta
         * - estraggo info tipo String
         * - aggiungo info a un testo generico che poi setto in display
         */

        String testoDisplay = "";

        for (int i = 0; i < listaCorsi.size(); i++) {
            // recupero un corso alla volta
            Corso c = listaCorsi.get(i);
            String info = c.getInfo();
            testoDisplay = info + testoDisplay;
        }

        // visualizzo i corsi in display
        tpDisplay.setText(testoDisplay);
    }

    private void salvaCorsi() {
        /*
         * - recupero un corso per volta
         * - estraggo info tipo String
         * - aggiungo info a un testo generico che poi setto in display
         */

        String testoDisplay = "";

        for (int i = 0; i < listaCorsi.size(); i++) {
            // recupero un corso alla volta
            Corso c = listaCorsi.get(i);
            String info = c.getInfo();
            testoDisplay += info;
        }

        // creo file corsi.txt
        try {
            FileWriter corsiTxt = new FileWriter("/home/tss/Viktor/OOP/GestioneScuola/file/corsi.txt");
            corsiTxt.write(testoDisplay);
            corsiTxt.close();
        } catch (IOException errore) {
            lblMsg.setText("Errore di scrittura file corsi.txt");
        }

    }

    private void salvaCorsiCsv() {
        /*
         * - recupero un corso per volta
         * - estraggo info tipo String
         * - aggiungo info a un testo generico che poi setto in display
         */

        String testoDisplay = "nomeCorso;durataCorso;descrizione;dataInizioCorso\n";

        for (int i = 0; i < listaCorsi.size(); i++) {
            // recupero un corso alla volta
            Corso c = listaCorsi.get(i);
            String info = c.getCsv();
            testoDisplay += info;
        }

        // creo file corsi.csv
        try {
            FileWriter corsiCsv = new FileWriter("/home/tss/Viktor/OOP/GestioneScuola/file/corsi.csv");
            corsiCsv.write(testoDisplay);
            corsiCsv.close();
        } catch (IOException errore) {
            lblMsg.setText("Errore di scrittura file corsi.csv");
        }

    }

    private void caricaDatiCorsi (){
        try {
            File fileCsv = new File("/home/tss/Viktor/OOP/GestioneScuola/file/corsi.csv");
            Scanner scannerFile = new Scanner (fileCsv);
            String riga = scannerFile.nextLine();
            while (scannerFile.hasNextLine()){
                /*
                riga = scannerFile.nextLine();
                String arrayDati[] = riga.split(";");
                String nomeCorso = arrayDati[0];
                String descrizione = arrayDati[0];
                String data = arrayDati[0];;
                String arrayData[] = data.split("-");
                int anno = Integer.parseInt(arrayData[0]);
                int mese = Integer.parseInt(arrayData[1]);
                int giorno = Integer.parseInt(arrayData[2]);
                String link = arrayDati[0];
                int durata = arrayDati[0];
                Corso nuovoCorso = new Corso(nomeCorso, durata, link, anno, mese, giorno);
                nuovoCorso.setDescrizioneCorso(descrizione);
                //nuovoCorso.setLink(link);
                */
            }
            
        } catch (Exception errore) {
            
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        txNomeCorso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txDescrizione = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        spDurata = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txDataInizio = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txLinkCorso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBCreaCorso = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpDisplay = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitolo.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Gestione scuola");

        jLabel1.setText("NomeCorso:");

        txDescrizione.setColumns(20);
        txDescrizione.setRows(5);
        jScrollPane1.setViewportView(txDescrizione);

        jLabel2.setText("Descrizione:");

        jLabel3.setText("Durata Ore:");

        txDataInizio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel4.setText("Data Inizio: ");

        jLabel5.setText("Link Corso:");

        jBCreaCorso.setText("Crea Corso");
        jBCreaCorso.addActionListener(new java.awt.event.addActionListener(){
            public void actionPerformed (java.awt.eventActionEvent evt) {
                btnCreaCorsoActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("DejaVu Math TeX Gyre", 1, 12)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 0, 0));

        jScrollPane2.setViewportView(tpDisplay);

        jLabel6.setText("(es.23/04/22)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(addActionListener
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitolo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCreaCorso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txLinkCorso)
                    .addComponent(txNomeCorso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spDurata, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txDataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitolo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNomeCorso, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(spDurata, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txDataInizio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLinkCorso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBCreaCorso)
                .addGap(18, 18, 18)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCreaCorso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JSpinner spDurata;
    private javax.swing.JTextPane tpDisplay;
    private javax.swing.JFormattedTextField txDataInizio;
    private javax.swing.JTextArea txDescrizione;
    private javax.swing.JTextField txLinkCorso;
    private javax.swing.JTextField txNomeCorso;
    // End of variables declaration//GEN-END:variables
}
